### ISSUE TITLE
🎨 [Chore] -  페이지 및 컴포넌트 분리

### ISSUE THREAD

**Issue by cweedlee** [maplepong/docker#22]
## 📝 Description
> 어떤 기능에 대해 요청할지
페이지 구조 파악이 어려움
현재 모든 페이지/컴포넌트가 컴포넌트에 들어가 있어서 시간날때 정리하고 싶음

## ✅ To-do

- [ ] 페이지 / 내부 컴포넌트 분리하기...

## 📚 Etc
- 특이사항

**Comment by siwolee** [comment]
안하기로함
